apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-4scm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-4scm
    app.kubernetes.io/part-of: tkrw-pr714-0075-0064-app
  name: devfile-sample-4scm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-4scm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-4scm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0064-tenant/tkrw-pr714-0075-0064-app/devfile-sample-4scm@sha256:bbaec12ad8889a763b3df594f33e65bd3ad8e08e1f3c6700f16feaf70c67ee6a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
